<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;
use App\Models\User;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // User::factory(10)->create();

        // DB::table('users')->insert([
        $usersData = [
            [
                'id' => '1',
                'username' => 'superadmin',
                'email' => 'admin@ppl.ac.id',
                'nickname' => 'superadmin',
                'fullname' => 'superadmin',
                'role_to_assign' => 'superadmin',
                'client_id' => '1',
                'title' => 'superadmin',
                'mobile' => '087765977700',
                'password' => Hash::make('password'),
            ],
            [
                'id' => '2',
                'username' => 'wawan',
                'email' => 'wawan@ppl.ac.id',
                'nickname' => 'wawan',
                'fullname' => 'Wawan Apriandi',
                'role_to_assign' => 'superadmin',
                'client_id' => '1',
                'title' => 'admin bmn',
                'mobile' => '087765432100',
                'password' => Hash::make('password'),
            ],
            [
                'id' => '3',
                'username' => 'roni',
                'email' => 'sahroni.fajrin@ppl.ac.id',
                'nickname' => 'roni',
                'fullname' => 'Sahroni Fajrin',
                'role_to_assign' => 'superadmin',
                'client_id' => '1',
                'title' => 'admin bmn',
                'mobile' => '082339966007',
                'password' => Hash::make('password'),
            ],
            [
                'id' => '4',
                'username' => 'kiki',
                'email' => 'kiki@ppl.ac.id',
                'nickname' => 'kiki',
                'fullname' => 'Kiki Pranoto',
                'role_to_assign' => 'admin_tik',
                'client_id' => '1',
                'title' => 'admin tik',
                'mobile' => '087765977700',
                'password' => Hash::make('password'),
            ],
            [
                // 'id' => '5',
                'username' => 'kadek',
                'email' => 'kadek@ppl.ac.id',
                'nickname' => 'kadek',
                'fullname' => 'Kadek Surianta',
                'role_to_assign' => 'admin_rt',
                'client_id' => '1',
                'title' => 'admin rt',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                // 'id' => '6', rizhki
                'username' => 'rizhki',
                'email' => 'rizhki@ppl.ac.id',
                'nickname' => 'rizhki',
                'fullname' => 'Rizhki Pahlawan Dwi Putra',
                'role_to_assign' => 'staf_tik',
                'client_id' => '1',
                'title' => 'staf tik',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                // 'id' => '7',
                'username' => 'zakaria',
                'email' => 'zakaria@ppl.ac.id',
                'nickname' => 'zakaria',
                'fullname' => 'Ahmad Zakaria',
                'role_to_assign' => 'staf_tik',
                'client_id' => '1',
                'title' => 'staf tik',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                // 'id' => '8',
                'username' => 'pati',
                'email' => 'pati@ppl.ac.id',
                'nickname' => 'pati',
                'fullname' => 'Pati Gustian',
                'role_to_assign' => 'staf_tik',
                'client_id' => '1',
                'title' => 'staf tik',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                // 'id' => '9',
                'username' => 'zaenal',
                'email' => 'zaenal@ppl.ac.id',
                'nickname' => 'zaenal',
                'fullname' => 'Zaenal Abidin',
                'role_to_assign' => 'staf_engineering',
                'client_id' => '1',
                'title' => 'staf engineering',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                // 'id' => '10',
                'username' => 'ramli',
                'email' => 'ramli@ppl.ac.id',
                'nickname' => 'ramli',
                'fullname' => 'Ramli Morales',
                'role_to_assign' => 'staf_driver',
                'client_id' => '1',
                'title' => 'staf driver',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'adak',
                'email' => 'adak@ppl.ac.id',
                'nickname' => 'ADAK',
                'fullname' => 'ADAK',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'ADAK',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'adum',
                'email' => 'adum@ppl.ac.id',
                'nickname' => 'ADUM',
                'fullname' => 'ADUM',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'ADUM',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'upw',
                'email' => 'upw@ppl.ac.id',
                'nickname' => 'Prodi UPW',
                'fullname' => 'Prodi UPW',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Prodi UPW',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'dik',
                'email' => 'dik@ppl.ac.id',
                'nickname' => 'Prodi DIK',
                'fullname' => 'Prodi DIK',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Prodi DIK',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'sku',
                'email' => 'sku@ppl.ac.id',
                'nickname' => 'Prodi SKU',
                'fullname' => 'Prodi SKU',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Prodi SKU',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'tah',
                'email' => 'tah@ppl.ac.id',
                'nickname' => 'Prodi TAH',
                'fullname' => 'Prodi TAH',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Prodi TAH',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'spm',
                'email' => 'spm@ppl.ac.id',
                'nickname' => 'SPM',
                'fullname' => 'SPM',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'SPM',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'pppm',
                'email' => 'pppm@ppl.ac.id',
                'nickname' => 'PPPM',
                'fullname' => 'PPPM',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'PPPM',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'spi',
                'email' => 'spi@ppl.ac.id',
                'nickname' => 'SPI',
                'fullname' => 'SPI',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'SPI',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'unit.bahasa',
                'email' => 'unit.bahasa@ppl.ac.id',
                'nickname' => 'Unit Bahasa',
                'fullname' => 'Unit Bahasa',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit Bahasa',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'pkn',
                'email' => 'pkn@ppl.ac.id',
                'nickname' => 'Unit PKN',
                'fullname' => 'Unit PKN',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit PKN',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'lsp',
                'email' => 'lsp@ppl.ac.id',
                'nickname' => 'LSP',
                'fullname' => 'LSP',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'LSP',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'unit.kewirausahaan',
                'email' => 'unit.kewirausahaan@ppl.ac.id',
                'nickname' => 'Unit Kewirausahaan',
                'fullname' => 'Unit Kewirausahaan',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit Kewirausahaan',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'unit.tilc',
                'email' => 'unit.tilc@ppl.ac.id',
                'nickname' => 'Unit TILC',
                'fullname' => 'Unit TILC',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit TILC',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'perpustakaan',
                'email' => 'perpustakaan@ppl.ac.id',
                'nickname' => 'Unit Perpustakaan',
                'fullname' => 'Unit Perpustakaan',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit Perpustakaan',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'tik',
                'email' => 'tik@ppl.ac.id',
                'nickname' => 'Unit TIK',
                'fullname' => 'Unit TIK',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit TIK',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'unit.humas',
                'email' => 'unit.humas@ppl.ac.id',
                'nickname' => 'Unit HUMAS',
                'fullname' => 'Unit HUMAS',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Unit HUMAS',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
            [
                'username' => 'klinik.pratama',
                'email' => 'klinik.pratama@ppl.ac.id',
                'nickname' => 'Klinik Pratama',
                'fullname' => 'Klinik Pratama',
                'role_to_assign' => 'user',
                'client_id' => '1',
                'title' => 'Klinik Pratama',
                'mobile' => '087777777777',
                'password' => Hash::make('password'),
            ],
        ];
        foreach ($usersData as $userData) {
            // Dan jangan gunakan 'id' secara eksplisit di create()
            // Biarkan Laravel membuat ID secara otomatis, atau jika kamu punya alasan kuat
            // untuk menggunakan ID statis, pastikan tabel users dikosongkan terlebih dahulu
            // atau tambahkan firstOrCreate jika id sudah ada.

            $roleToAssign = $userData['role_to_assign'];
            unset($userData['role_to_assign']); // Hapus key ini agar tidak masuk ke DB

            $user = User::firstOrCreate(
                ['email' => $userData['email']], // Kriteria unik untuk mencari user
                $userData // Data untuk membuat user baru jika tidak ditemukan
            );

            // Assign role ke user yang baru dibuat atau yang sudah ada
            $user->assignRole($roleToAssign);
        }
    }
}
